In [ ]:
!nvidia-smi


Tue Feb  3 16:26:35 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import os
os.listdir()



['.config', 'Test.csv', 'Train.csv', 'Val.csv', 'sample_data']

In [ ]:
import pandas as pd

train = pd.read_csv("Train.csv")
val   = pd.read_csv("Val.csv")
test  = pd.read_csv("Test.csv")

print("Train shape:", train.shape)
print("Columns:", train.columns)
train.head(3)


Train shape: (12575, 2)
Columns: Index(['Data', 'Label'], dtype='object')


Data  Label
0  মুগ্ধ হয়ে গেলাম মামু. আর তোমায় কি কমু. বলো তোম...      1
1  এই কুত্তার বাচ্চাদের জন্য দেশটা আজ এমন অবস্তায়...      2
2                          ভাই আপনার কথাই যাদু রয়েছে      1

In [ ]:
print("Train labels:", sorted(train["Label"].unique()))
print("Val labels:", sorted(val["Label"].unique()))
print("Test labels:", sorted(test["Label"].unique()))


Train labels: [np.int64(0), np.int64(1), np.int64(2)]
Val labels: [np.int64(0), np.int64(1), np.int64(2)]
Test labels: [np.int64(0), np.int64(1), np.int64(2)]


In [ ]:
print(train["Label"].value_counts())


Label
1    5133
2    4548
0    2894
Name: count, dtype: int64


In [ ]:
from transformers import pipeline

MODEL_NAME = "cardiffnlp/twitter-xlm-roberta-base-sentiment"
clf = pipeline("text-classification", model=MODEL_NAME)

print(clf("আমি আজকে খুব খুশি"))
print(clf("খুব খারাপ সার্ভিস"))


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  | 
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[{'label': 'positive', 'score': 0.7924331426620483}]
[{'label': 'negative', 'score': 0.8623208403587341}]


In [ ]:
import pandas as pd

# Make a clean copy with standard column names
train_df = train.rename(columns={"Data":"text", "Label":"label"}).copy()
val_df   = val.rename(columns={"Data":"text", "Label":"label"}).copy()
test_df  = test.rename(columns={"Data":"text", "Label":"label"}).copy()

# Convert label to int
train_df["label"] = train_df["label"].astype(int)
val_df["label"]   = val_df["label"].astype(int)
test_df["label"]  = test_df["label"].astype(int)

train_df.head(3)


text  label
0  মুগ্ধ হয়ে গেলাম মামু. আর তোমায় কি কমু. বলো তোম...      1
1  এই কুত্তার বাচ্চাদের জন্য দেশটা আজ এমন অবস্তায়...      2
2                          ভাই আপনার কথাই যাদু রয়েছে      1

In [ ]:
min_label = min(train_df["label"].unique())
print("Min label:", min_label)


Min label: 0


In [ ]:
!pip -q install -U transformers accelerate datasets evaluate


In [ ]:
!pip -q install --upgrade --no-cache-dir \
  "pandas==2.2.2" \
  "requests==2.32.4"



In [ ]:
!pip -q install --upgrade --no-cache-dir \
  "pyarrow>=21.0.0" \
  "datasets>=4.5.0" \
  "transformers" "accelerate" "evaluate" "scikit-learn"



In [ ]:
import numpy as np, pandas as pd
import pyarrow as pa, datasets, transformers

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("pyarrow:", pa.__version__)
print("datasets:", datasets.__version__)
print("transformers:", transformers.__version__)



numpy: 2.0.2
pandas: 2.2.2
pyarrow: 23.0.0
datasets: 4.5.0
transformers: 5.0.0


In [ ]:
import torch
print("GPU available:", torch.cuda.is_available())
!nvidia-smi


GPU available: True
Tue Feb  3 16:36:27 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P0             28W /   70W |    1244MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+---------------------------

In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"


In [ ]:
import numpy as np
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from transformers import DataCollatorWithPadding
import evaluate

MODEL_NAME = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

# number of classes from your data
NUM_LABELS = len(sorted(train_df["label"].unique()))
print("NUM_LABELS =", NUM_LABELS)

# ✅ define tokenizer first
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# ✅ then create collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def to_ds(df):
    df = df[["text","label"]].copy()
    df["text"] = df["text"].astype(str)
    df["label"] = df["label"].astype(int)
    return Dataset.from_pandas(df)

train_ds = to_ds(train_df)
val_ds   = to_ds(val_df)
test_ds  = to_ds(test_df)

def tok(batch):
    return tokenizer(batch["text"], truncation=True)

train_ds = train_ds.map(tok, batched=True)
val_ds   = val_ds.map(tok, batched=True)
test_ds  = test_ds.map(tok, batched=True)

train_ds.set_format("torch", columns=["input_ids","attention_mask","label"])
val_ds.set_format("torch", columns=["input_ids","attention_mask","label"])
test_ds.set_format("torch", columns=["input_ids","attention_mask","label"])

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME, num_labels=NUM_LABELS, ignore_mismatched_sizes=True
)

acc = evaluate.load("accuracy")
f1  = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": acc.compute(predictions=preds, references=labels)["accuracy"],
        "macro_f1": f1.compute(predictions=preds, references=labels, average="macro")["f1"]
    }

args = TrainingArguments(
    output_dir="xlmr_finetuned_bn",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    logging_steps=50,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()
print("FINAL TEST:", trainer.evaluate(test_ds))



NUM_LABELS = 3


Map:   0%|          | 0/12575 [00:00<?, ? examples/s]

Map:   0%|          | 0/1567 [00:00<?, ? examples/s]

Map:   0%|          | 0/1586 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  | 
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.Laye

FINAL TEST: {'eval_loss': 0.8018025159835815, 'eval_accuracy': 0.7131147540983607, 'eval_macro_f1': 0.6853093032869144, 'eval_runtime': 6.3271, 'eval_samples_per_second': 250.667, 'eval_steps_per_second': 31.452, 'epoch': 3.0}


In [ ]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

pred = trainer.predict(test_ds)
y_pred = np.argmax(pred.predictions, axis=1)
y_true = pred.label_ids

print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
print("\nClassification Report:\n", classification_report(y_true, y_pred, digits=4))


Confusion Matrix:
 [[185  91  85]
 [ 96 511  47]
 [ 80  56 435]]

Classification Report:
               precision    recall  f1-score   support

           0     0.5125    0.5125    0.5125       361
           1     0.7766    0.7813    0.7790       654
           2     0.7672    0.7618    0.7645       571

    accuracy                         0.7131      1586
   macro avg     0.6854    0.6852    0.6853      1586
weighted avg     0.7131    0.7131    0.7131      1586



In [ ]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Get predictions on test set
pred = trainer.predict(test_ds)
y_pred = np.argmax(pred.predictions, axis=1)
y_true = pred.label_ids  # safest (from dataset)

# Label names MUST match your numeric labels (0,1,2)
label_names = ["neutral", "positive", "negative"]   # change if your mapping is different

print(classification_report(y_true, y_pred, target_names=label_names, digits=4))
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))


              precision    recall  f1-score   support

     neutral     0.5125    0.5125    0.5125       361
    positive     0.7766    0.7813    0.7790       654
    negative     0.7672    0.7618    0.7645       571

    accuracy                         0.7131      1586
   macro avg     0.6854    0.6852    0.6853      1586
weighted avg     0.7131    0.7131    0.7131      1586

Confusion Matrix:
 [[185  91  85]
 [ 96 511  47]
 [ 80  56 435]]


In [ ]:
#no-preprocessing
def run_experiment(train_df, val_df, test_df, exp_name="baseline"):
    import numpy as np
    from datasets import Dataset
    from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
    from transformers import DataCollatorWithPadding
    import evaluate

    MODEL_NAME = "cardiffnlp/twitter-xlm-roberta-base-sentiment"

    NUM_LABELS = len(sorted(train_df["label"].unique()))
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    def to_ds(df):
        df = df[["text","label"]].copy()
        df["text"] = df["text"].astype(str)
        df["label"] = df["label"].astype(int)
        return Dataset.from_pandas(df)

    train_ds = to_ds(train_df)
    val_ds   = to_ds(val_df)
    test_ds  = to_ds(test_df)

    def tok(batch):
        return tokenizer(batch["text"], truncation=True, max_length=128)

    train_ds = train_ds.map(tok, batched=True)
    val_ds   = val_ds.map(tok, batched=True)
    test_ds  = test_ds.map(tok, batched=True)

    train_ds.set_format("torch", columns=["input_ids","attention_mask","label"])
    val_ds.set_format("torch", columns=["input_ids","attention_mask","label"])
    test_ds.set_format("torch", columns=["input_ids","attention_mask","label"])

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME, num_labels=NUM_LABELS, ignore_mismatched_sizes=True
    )

    acc = evaluate.load("accuracy")
    f1  = evaluate.load("f1")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=1)
        return {
            "accuracy": acc.compute(predictions=preds, references=labels)["accuracy"],
            "macro_f1": f1.compute(predictions=preds, references=labels, average="macro")["f1"]
        }

    args = TrainingArguments(
        output_dir=f"out_{exp_name}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=3,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="macro_f1",
        logging_steps=50,
        report_to="none",
        seed=42
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=data_collator,
        compute_metrics=compute_metrics
    )

    trainer.train()
    val_result  = trainer.evaluate(val_ds)
    test_result = trainer.evaluate(test_ds)

    return val_result, test_result

In [ ]:
#run without preprocessing
# Create standardized dataframes
train_df = train.rename(columns={"Data":"text", "Label":"label"}).copy()
val_df   = val.rename(columns={"Data":"text", "Label":"label"}).copy()
test_df  = test.rename(columns={"Data":"text", "Label":"label"}).copy()

# Make sure labels are integers
train_df["label"] = train_df["label"].astype(int)
val_df["label"]   = val_df["label"].astype(int)
test_df["label"]  = test_df["label"].astype(int)

print(train_df.columns)
train_df.head(3)

Index(['text', 'label'], dtype='object')


text  label
0  মুগ্ধ হয়ে গেলাম মামু. আর তোমায় কি কমু. বলো তোম...      1
1  এই কুত্তার বাচ্চাদের জন্য দেশটা আজ এমন অবস্তায়...      2
2                          ভাই আপনার কথাই যাদু রয়েছে      1

In [ ]:
val_base, test_base = run_experiment(train_df, val_df, test_df, "baseline")
print("BASELINE VAL:", val_base)
print("BASELINE TEST:", test_base)

Map:   0%|          | 0/12575 [00:00<?, ? examples/s]

Map:   0%|          | 0/1567 [00:00<?, ? examples/s]

Map:   0%|          | 0/1586 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  | 
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.Laye

BASELINE VAL: {'eval_loss': 0.768182635307312, 'eval_accuracy': 0.7217613273771538, 'eval_macro_f1': 0.6926973872607783, 'eval_runtime': 6.6881, 'eval_samples_per_second': 234.296, 'eval_steps_per_second': 29.306, 'epoch': 3.0}
BASELINE TEST: {'eval_loss': 0.8018025159835815, 'eval_accuracy': 0.7131147540983607, 'eval_macro_f1': 0.6853093032869144, 'eval_runtime': 8.291, 'eval_samples_per_second': 191.291, 'eval_steps_per_second': 24.002, 'epoch': 3.0}


In [ ]:
#Put this “Preprocessing Functions” cell once
import re, unicodedata

# remove invisible characters common in Bangla copy-paste
ZERO_WIDTH = r"[\u200b\u200c\u200d\uFEFF]"
multi_space_re = re.compile(r"\s+")

url_re = re.compile(r"http\S+|www\.\S+")
mention_re = re.compile(r"@\w+")
rt_re = re.compile(r"^RT\s+@\w+:\s*")

repeat_punct_re = re.compile(r"([!?।])\1{2,}")   # !!!!! or ????

bn_to_en_digits = str.maketrans("০১২৩৪৫৬৭৮৯", "0123456789")

def preprocess_v1(text: str) -> str:
    """V1: Safe cleaning (Unicode normalize + zero-width remove + spacing)"""
    text = "" if text is None else str(text)
    text = unicodedata.normalize("NFKC", text)
    text = re.sub(ZERO_WIDTH, "", text)
    text = multi_space_re.sub(" ", text).strip()
    return text

def preprocess_v2(text: str) -> str:
    """V2: Twitter normalization (V1 + mask URL + mask USER + remove RT header)"""
    text = preprocess_v1(text)
    text = rt_re.sub("", text)
    text = url_re.sub(" [URL] ", text)
    text = mention_re.sub(" [USER] ", text)
    text = multi_space_re.sub(" ", text).strip()
    return text

def preprocess_v3(text: str) -> str:
    """V3: V2 + normalize Bangla digits + compress repeated punctuation"""
    text = preprocess_v2(text)
    text = text.translate(bn_to_en_digits)
    text = repeat_punct_re.sub(r"\1\1", text)  # "!!!!!" -> "!!"
    text = multi_space_re.sub(" ", text).strip()
    return text



In [ ]:
#Run your 3 preprocessing experiments (like baseline)
#Preprocess V1 experiment
train_v1 = train_df.copy()
val_v1   = val_df.copy()
test_v1  = test_df.copy()

for df in [train_v1, val_v1, test_v1]:
    df["text"] = df["text"].apply(preprocess_v1)

val_v1_res, test_v1_res = run_experiment(train_v1, val_v1, test_v1, "preprocess_v1")
print("V1 VAL:", val_v1_res)
print("V1 TEST:", test_v1_res)



Map:   0%|          | 0/12575 [00:00<?, ? examples/s]

Map:   0%|          | 0/1567 [00:00<?, ? examples/s]

Map:   0%|          | 0/1586 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  | 
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.Laye

V1 VAL: {'eval_loss': 0.7572673559188843, 'eval_accuracy': 0.7236758136566688, 'eval_macro_f1': 0.6961044944711525, 'eval_runtime': 6.1542, 'eval_samples_per_second': 254.622, 'eval_steps_per_second': 31.848, 'epoch': 3.0}
V1 TEST: {'eval_loss': 0.7819272875785828, 'eval_accuracy': 0.7175283732660782, 'eval_macro_f1': 0.6862810640986297, 'eval_runtime': 6.3517, 'eval_samples_per_second': 249.699, 'eval_steps_per_second': 31.33, 'epoch': 3.0}


In [ ]:
#Preprocess V2 experiment

train_v2 = train_df.copy()
val_v2   = val_df.copy()
test_v2  = test_df.copy()

for df in [train_v2, val_v2, test_v2]:
    df["text"] = df["text"].apply(preprocess_v2)

val_v2_res, test_v2_res = run_experiment(train_v2, val_v2, test_v2, "preprocess_v2")
print("V2 VAL:", val_v2_res)
print("V2 TEST:", test_v2_res)


Map:   0%|          | 0/12575 [00:00<?, ? examples/s]

Map:   0%|          | 0/1567 [00:00<?, ? examples/s]

Map:   0%|          | 0/1586 [00:00<?, ? examples/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-xlm-roberta-base-sentiment
Key                             | Status     |  | 
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.Laye

V2 VAL: {'eval_loss': 0.7550526261329651, 'eval_accuracy': 0.7230376515634971, 'eval_macro_f1': 0.6948261266261166, 'eval_runtime': 6.1931, 'eval_samples_per_second': 253.024, 'eval_steps_per_second': 31.648, 'epoch': 3.0}
V2 TEST: {'eval_loss': 0.7827208638191223, 'eval_accuracy': 0.7175283732660782, 'eval_macro_f1': 0.6865648561421716, 'eval_runtime': 7.2281, 'eval_samples_per_second': 219.421, 'eval_steps_per_second': 27.531, 'epoch': 3.0}


In [ ]:
#Preprocess V3 experiment
train_v3 = train_df.copy()
val_v3   = val_df.copy()
test_v3  = test_df.copy()

for df in [train_v3, val_v3, test_v3]:
    df["text"] = df["text"].apply(preprocess_v3)

val_v3_res, test_v3_res = run_experiment(train_v3, val_v3, test_v3, "preprocess_v3")
print("V3 VAL:", val_v3_res)
print("V3 TEST:", test_v3_res)


In [ ]:
#Compare results nicely
results = {
    "baseline": (val_base["eval_macro_f1"], test_base["eval_macro_f1"]),
    "v1": (val_v1_res["eval_macro_f1"], test_v1_res["eval_macro_f1"]),
    "v2": (val_v2_res["eval_macro_f1"], test_v2_res["eval_macro_f1"]),
    "v3": (val_v3_res["eval_macro_f1"], test_v3_res["eval_macro_f1"]),
}

for k, (v_f1, t_f1) in results.items():
    print(f"{k:8s} | VAL macro-F1: {v_f1:.4f} | TEST macro-F1: {t_f1:.4f}")


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
!mkdir -p /content/drive/MyDrive/colab_project


In [ ]:
!mv out_baseline /content/drive/MyDrive/colab_project/
!mv out_preprocess_v1 /content/drive/MyDrive/colab_project/
!mv out_preprocess_v2 /content/drive/MyDrive/colab_project/
!mv sample_data /content/drive/MyDrive/colab_project/
!mv xlmr_finetuned_bn /content/drive/MyDrive/colab_project/

!mv Train.csv /content/drive/MyDrive/colab_project/
!mv Val.csv /content/drive/MyDrive/colab_project/
!mv Test.csv /content/drive/MyDrive/colab_project/


^C
